services:
  mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-init:/docker-entrypoint-initdb.d/
    restart: always
    container_name: smartcart_mongo
    networks:
      - smartnet

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    container_name: smartcart_backend
    networks:
      - smartnet

  ml_service:
    build:
      context: ./analytics_service
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    container_name: smartcart_ml_service
    networks:
      - smartnet

  frontend:
    build:
      context: ./ui
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    depends_on:
      - backend
    container_name: smartcart_frontend
    networks:
      - smartnet

  nodered:
    image: nodered/node-red
    container_name: smartcart_nodered
    ports:
      - "1880:1880"
    depends_on:
      - backend
      - ml_service
    networks:
      - smartnet

networks:
  smartnet:

